language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit